config/routes.rb
Rails.application.routes.draw do

   root 'welcome#home'

   get '/sign-up' => 'signup#new', as: :signup
   post '/sign-up' => 'signup#create'
   get '/sign-in' => 'signin#new', as: :signin
   post '/sign-in' => 'signin#create'
   get '/sign-out' => 'signin#destroy', as: :signout
   get '/search' => 'posts#search'
   get '/old-sort' => 'favorites#oldest_sort'
   get '/new-sort' => 'favorites#newest_sort'
   get '/map' =>'posts#map'

  resources :users
  resources :posts do
    resources :comments
  end
  resources :favorites

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:username,:email,:password,:password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/new.html.erb
<div class="ui centered grid">
  <div class="six wide column">
    <%= form_for @user, url: sign_up_path do |f| %>
      <center><h1>Sign Up For ChowSpana</h1></center>

      <center>
        <div id="signUpField" class="ui input">
          <%= f.label :username %>
          <%= f.text_field :username %>
        </div>
      </center>

    <center>
      <div id="signUpField" class="ui input">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
    </center>

    <center>
      <div id="signUpField" class="ui input">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
    </center>

    <center>
      <div id="signUpField" class="ui input">
       <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
    </center>

    <center>
      <div>
        <%= f.submit "Sign up", class:"ui red button"%>
      </div>
    </center>

    <% end %>
  </div>
</div>