config/routes.rb
Rails.application.routes.draw do

   root 'welcome#home'

   get '/sign-up' => 'signup#new', as: :signup
   post '/sign-up' => 'signup#create'
   get '/sign-in' => 'signin#new', as: :signin
   post '/sign-in' => 'signin#create'
   get '/sign-out' => 'signin#destroy', as: :signout
   get '/search' => 'posts#search'
   get '/old-sort' => 'favorites#oldest_sort'
   get '/new-sort' => 'favorites#newest_sort'
   get '/map' =>'posts#map'

  resources :users
  resources :posts do
    resources :comments
  end
  resources :favorites

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/views/welcome/home.html.erb
<!-- <div>
  <% if current_user %>
  <%= link_to "Post Your Find!", new_post_path %>
  |
  <%= link_to "View All Finds!", posts_path%>
  <% else %>
  <%= link_to "View All Finds!", posts_path%>
  <%= link_to "Sign Up", signup_path %>
  <%= link_to "Sign In", signin_path %>
  <% end %>
</div> -->

<div class="ui two column centered grid">
  <% if current_user %>
  <div class="three column row centered">
    <div class="column">
      <a href="/posts">
        <div class="homeSegment ui segment">
          <center class="currentHomeSegment">
            <h2>View All Finds!</h2>
            <%= image_tag "menu21.png", :class => 'homeSegmentImg'%>
          </center>
        </div>
      </a>
    </div>
    <div class="column">
      <a href="/favorites">
        <div class="homeSegment ui segment">
          <center class="currentHomeSegment">
            <h2>View Your Favorites!</h2>
            <%= image_tag "juiceBigger.png", :class => 'homeSegmentImg'%>
          </center>
        </div>
      </a>
    </div>
    <div class="column">
      <a href="/posts/new">
        <div class="homeSegment ui segment">
          <center class="currentHomeSegment">
            <h2>Post A Find!</h2>
            <%= image_tag "covered16.png", :class => 'homeSegmentImg'%>
          </center>
        </div>
      </a>
    </div>
  </div>

  <% else %>
    <div class="three column row centered">
        <div class="column">
          <a id="homeSignUpLink" href="/sign-up">
            <div class="ui segment homeSegment">
              <center class="innerHomeSegment">
                <div id="popaisleImg">

                </div>
               <h1>Sign Up</h1>
               <div id="storeImg">
               </div>
              </center>
            </div>
          </a>
        </div>

        <div class="column">
          <a id="homeSignInLink" href="/sign-in">
            <div class="ui segment homeSegment">
              <center class="innerHomeSegment">
                <div id="candyaisleImg">
                </div>
                <h1 id="signinLink">Sign In</h1>
                <div id="poprackImg">
                </div>
              </center>
            </div>
          </a>
        </div>
    </div>
  <% end %>
</div>