config/routes.rb
Rails.application.routes.draw do

   root 'welcome#home'

   get '/sign-up' => 'signup#new', as: :signup
   post '/sign-up' => 'signup#create'
   get '/sign-in' => 'signin#new', as: :signin
   post '/sign-in' => 'signin#create'
   get '/sign-out' => 'signin#destroy', as: :signout
   get '/search' => 'posts#search'
   get '/old-sort' => 'favorites#oldest_sort'
   get '/new-sort' => 'favorites#newest_sort'
   get '/map' =>'posts#map'

  resources :users
  resources :posts do
    resources :comments
  end
  resources :favorites

end

app/models/post.rb
class Post < ActiveRecord::Base

  def full_address
    [address, city, state].compact.join(', ')
  end
  #
  # geocoded_by full_address(:address,:city,:state)
  # def full_address
  #   "#{self.address}, #{self.city}, #{self.state}"
  # end

  geocoded_by :full_address

  after_validation :geocode, :if => :address_changed?

  self.per_page = 3

  belongs_to :user
  has_many :comments

  validates :productname, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true


  has_attached_file :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
     # @posts = Post.all.sort_by &:created_at
     @posts = Post.paginate(:page => params[:page]).order('created_at DESC')
  end

  def new
    if current_user.nil?
      redirect_to root_path
      return
    end
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)
    if current_user.nil?
      redirect_to posts_path
    end

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def search
    @searchTerm = params[:keyTerm].downcase
    @posts = Post.where("lower(productname) like ? or lower(city) like ?", "%#{@searchTerm}%", "%#{@searchTerm}%").paginate(:page => params[:page])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if current_user.id == @post.user_id
      if @post.update(post_params)
        redirect_to @post
      else
        render "edit"
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user.id == @post.user_id
      @post.destroy
      redirect_to posts_path
    else
      redirect_to @post
    end
  end

  def map
    @posts = Post.all


    #  @locations = @posts.map do |post|
    #    if post.latitude.nil?
    #      nil
    #    else
    #      [post.latitude, post.longitude]
    #    end
    # end.compact
    # render json: @locations
    @locations = @posts.map do |post|
      if post.latitude.nil?
        nil
      else
        {
          type: 'Feature',
          "geometry" => { "type"=> "Point", "coordinates"=> [post.longitude, post.latitude]},
          "properties" => {
            "image"=> post.image.url,
            "marker-symbol"=> "star",
            "marker-color"=> "#ff8888",
            "marker-size"=> "large",
            "product_name"=> post.productname,
            "post_id"=> post.id,
            "city"=> post.city,
            "state"=> post.state
          }
        }
      end
    end.compact
    # render json: @locations



  end

  private

  def post_params
    params.require(:post).permit(
    :productname,
    :description,
    :price,
    :location,
    :address,
    :city,
    :state,
    :image,
    :user_id,
    :latitude,
    :longitude
    )
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<center><h1><%= "Editing #{@post.productname}" %></h1></center>

<div id="postIndexMainGrid" class="ui centered grid">
  <div class="eight wide column postFormGrid">
    <div class="postForm">
      <%= form_for @post do |f| %>

      <div class="ui input postFormInput">
        <%= f.label "Product Name" %>
        <%= f.text_field :productname %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :decription %>
        <%= f.text_area :description %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :price %>
        <%= f.text_field :price, :placeholder => "Note Type ($,€,£,etc...)" %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :location %>
        <%= f.text_field :location %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>

      <div class="postFormInput">
        <%= f.file_field :image %>
      </div>

      <div class="postFormButtons">
        <%= f.submit "Submit", class: "ui red button" %>
        <%= link_to "Back", posts_path, class:"ui button" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="three column row centered">
  <div id="NavColumn" class="column ui">
    <div id="NavSegment" class="ui segment">
      <center><h3 id="NavSegmentHeader"><%= "Hello, #{current_user.username}" %></h3></center>
      <center class="userMenuButtons"><%= link_to "Post A Find", new_post_path, class:"ui small button userMenuNewPostButton" %></center>
      <center class="userMenuButtons"><%= link_to "View Your Favorites", favorites_path, class:"ui small button userMenuFavoritesButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds On Map", map_path, class:"ui small button userMenuHomeButton" %></center>
    </div>
  </div>
</div>

<div class="ui grid userShowHeader">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <center>
      <h1 id="indexHeader"><%="All Finds" %></h1>
      <div class="apple_pagination">
        <%= will_paginate @posts, :container => false %>
      </div>
      <div id="indexNavFilter" class="ui input">
        <form id="form_id" action="/search" method="get">
          <p>
            Search All Finds:
          </p>
          <input name="keyTerm" class="searchBox" type="text" placeholder="Enter Product or City">
        </form>
      </div>
    </center>
  </div>
</div>

<% @posts.each do |post| %>
<div class="ui grid postIndexMainGrid">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <div id="indexPost">
      <div id="indexProName">
        <h1><%= link_to "#{post.productname}", post %></h1>
      </div>

      <div id="postIndexPic" class="two wide column userShowImage">
        <%= image_tag post.image.url %>
      </div>

      <div class="product-details user-show">
        <div id="indexProLoc">
          <h3><%= "Spotted In: #{post.city}, #{post.state}"%></h3>
        </div>

        <div id="indexProPrice">
          <h3><%= "Price: #{post.price}"%></h3>
        </div>

        <div id="indexProUser">
          <h3>
            <%= "Posted By:" %>
            <%=link_to "#{post.user.username}", post.user %>
          </h3>
        </div>

        <div class="postStaticMap">
          <span class="staticMapLink">Click To View/Hide Location</span>
          <div class="postStaticImage hidden">
            <% if post.latitude.nil? || post.longitude.nil? %>
            <h2>Location Details Invalid</h2>
            <% else %>
            <!-- <%= image_tag "http://api.tiles.mapbox.com/v4/michaeldean147.lk8hfgn9/#{post.longitude},#{post.latitude},4/400x200.jpg?access_token=pk.eyJ1IjoibWljaGFlbGRlYW4xNDciLCJhIjoiWjFIU0xOTSJ9.Dny6ilJR7MyqNy5HfffYgQ"%> -->
            <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{post.latitude},#{post.longitude}&zoom=15&size=300x200&markers=color:red%7C#{post.latitude},#{post.longitude}"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="ui grid pageFooter">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <div class="apple_pagination">
      <%= will_paginate @posts, :container => false %>
      <div class="page_info">
        <%= page_entries_info @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/map.html.erb
<div class="three column row centered">
  <div id="NavColumn" class="column ui">
    <div id="NavSegment" class="ui segment">
      <center><h3 id="NavSegmentHeader"><%= "Hello, #{current_user.username}" %></h3></center>
      <center class="userMenuButtons"><%= link_to "Post A Find", new_post_path, class:"ui small button userMenuNewPostButton" %></center>
      <center class="userMenuButtons"><%= link_to "View Your Favorites", favorites_path, class:"ui small button userMenuFavoritesButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds", posts_path, class:"ui small button userMenuHomeButton" %></center>
    </div>
  </div>
</div>

<div class="ui grid">
  <div id="mapGrid" class="right floated left aligned eleven wide column">
    <div id='map'></div>
  </div>
</div>

<script charset="utf-8">
  $(function(){
    L.mapbox.accessToken = 'pk.eyJ1IjoibWljaGFlbGRlYW4xNDciLCJhIjoiWjFIU0xOTSJ9.Dny6ilJR7MyqNy5HfffYgQ';
    var map = L.mapbox.map('map', 'michaeldean147.lk8ij07j')
    .setView([39.504, -99.976], 4);

    var markers = <%= raw @locations.to_json %>;
    markers.forEach(function(location) {
      console.log(location.properties.image)
        L.marker([location.geometry.coordinates[1], location.geometry.coordinates[0]]).bindPopup(
          '<div class="mapPostImage">\
            <img src="'+ location.properties.image+ '" alt="">\
          </div>\
          <div>\
            <h5>'+ location.properties.product_name +'</h5>\
          </div>\
          <div>\
            <p>'+ location.properties.city +','+ location.properties.state+'</p>\
          </div>\
          <div>\
          <a href="posts/' + location.properties.post_id +'"class="css_class">View This Post</a>\
          </div>')
        .addTo(map);
    });
  });
</script>

app/views/posts/new.html.erb
<center><h1>Post Your Find!</h1></center>

<div class="ui centered grid postIndexMainGrid">
  <div class="eight wide column postFormGrid">
    <div class="postForm">
      <%= form_for @post do |f| %>

      <div class="ui input postFormInput">
        <%= f.label "Product Name" %>
        <%= f.text_field :productname %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :decription %><br>
        <%= f.text_area :description %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :price %>
        <%= f.text_field :price, :placeholder => "Note Type ($,€,£,etc...)" %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :location %>
        <%= f.text_field :location %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div class="ui input postFormInput">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>

      <div class="postFormInput">
        <%= f.file_field :image %>
      </div>

      <div class="postFormButtons">
          <%= f.submit "Submit", class: "ui red button" %>
          <%= link_to "Back", posts_path, class:"ui button" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="three column row centered">
  <div id="NavColumn" class="column ui">
    <div id="NavSegment" class="ui segment">
      <center><h3 id="NavSegmentHeader"><%= "Hello, #{current_user.username}" %></h3></center>
      <center class="userMenuButtons"><%= link_to "Post A Find", new_post_path, class:"ui small button userMenuNewPostButton" %></center>
      <center class="userMenuButtons"><%= link_to "View Your Favorites", favorites_path, class:"ui small button userMenuFavoritesButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds", posts_path, class:"ui small button userMenuHomeButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds On Map", map_path, class:"ui small button userMenuHomeButton" %></center>
    </div>
  </div>
</div>

<div class="ui grid userShowHeader">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <center>
      <h1 id="indexHeader"><%="Results for '#{@searchTerm}'" %></h1>
      <div class="apple_pagination">
        <%= will_paginate @posts, :container => false %>
      </div>
      <div id="indexNavFilter" class="ui input">
        <form id="form_id" action="/search" method="get">
          <p>
            Search All Finds:
          </p>
          <input name="keyTerm" class="searchBox" type="text" placeholder="Enter Product or City">
        </form>
      </div>
    </center>
  </div>
</div>

<% @posts.each do |post| %>
<div class="ui grid postIndexMainGrid">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <div id="indexPost">
      <div id="indexProName">
        <h1><%= link_to "#{post.productname}", post %></h1>
      </div>

      <div id="postIndexPic" class="two wide column userShowImage">
        <%= image_tag post.image.url %>
      </div>

      <div class="product-details user-show">
        <div id="indexProLoc">
          <h3><%= "Spotted In: #{post.city}, #{post.state}"%></h3>
        </div>

        <div id="indexProPrice">
          <h3><%= "Price: #{post.price}"%></h3>
        </div>

        <div id="indexProUser">
          <h3>
            <%= "Posted By:" %>
            <%=link_to "#{post.user.username}", post.user %>
          </h3>
        </div>

        <div class="postStaticMap">
          <span class="staticMapLink">Click To View/Hide Location</span>
          <div class="postStaticImage hidden">
            <% if post.latitude.nil? || post.longitude.nil? %>
            <h2>Location Details Invalid</h2>
            <% else %>
            <!-- <%= image_tag "http://api.tiles.mapbox.com/v4/michaeldean147.lk8hfgn9/#{post.longitude},#{post.latitude},4/400x200.jpg?access_token=pk.eyJ1IjoibWljaGFlbGRlYW4xNDciLCJhIjoiWjFIU0xOTSJ9.Dny6ilJR7MyqNy5HfffYgQ"%> -->
            <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{post.latitude},#{post.longitude}&zoom=15&size=300x200&markers=color:red%7C#{post.latitude},#{post.longitude}"%>
            <% end %>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>
<% end %>

<div class="ui grid">
  <div id="postIndexGrids" class="right floated left aligned eight wide column">
    <div class="apple_pagination">
      <%= will_paginate @posts, :container => false %>
      <div class="page_info">
        <%= page_entries_info @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="three column row centered">
  <div id="NavColumn" class="column">
    <div id="postShowNavSegment" class="ui segment">
      <center class="userMenuButtons"><h3 id="NavSegmentHeader"><%= "Hello, #{current_user.username}" %></h3></center>
      <center class="userMenuButtons"><%= link_to "Post A Find", new_post_path, class:"ui small button userMenuNewPostButton" %></center>
      <center class="userMenuButtons"><%= link_to "View Your Favorites", favorites_path, class:"ui small button userMenuFavoritesButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds", posts_path, class:"ui small button userMenuHomeButton" %></center>
      <center class="userMenuButtons"><%= link_to "View All Finds On Map", map_path, class:"ui small button userMenuHomeButton" %></center>

      <center><h3 id="SegmentHeader"><%= "Post Options" %></h3></center>
      <center class= "userMenuButtons"> <%= link_to "Add A Comment", new_post_comment_path(@post), class:"ui small button userMenuNewPostButton" %></center>
      <% if current_user && current_user.id == @post.user_id %>
      <center class="userMenuButtons"><%= link_to "Edit Post", edit_post_path(@post), class:"ui small button userMenuNewPostButton" %></center>
      <center class="userMenuButtons"><%= link_to "Destroy Post", @post , method: :delete, data: {confirm: "Are You Sure?"}, class:"ui small button userMenuNewPostButton" %></center>
      <% else %>
        <% if !current_user.favorited_posts.include?(@post) %>
          <center class="userMenuButtons">
            <%= link_to "Favorite This Post!", favorites_path(post: @post), method: :post, class:"ui small button userMenuNewPostButton" %>
          </center>
        <% else %>
        <center class="userMenuButtons">
          <%= link_to "Remove From Favorites", favorite_path(@post) , method: :delete, data: {confirm: "Are You Sure?"}, class:"ui small button userMenuNewPostButton" %>
        </center>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="ui grid userShowHeader">
  <div id="postIndexGrids" class="right floated left aligned ten wide column">
    <center>
      <h1 id="indexHeader"><%=@post.productname%></h1>
    </center>
  </div>
</div>

<div class="ui grid postIndexMainGrid">
  <div id="postIndexGrids" class="right floated left aligned ten wide column">
    <div id="indexPost">
      <div id="postIndexPic" class="one wide column">
        <%= image_tag @post.image.url %>
      </div>

      <div class="product-details in-show">
        <div>
          <p><%= @post.description %></p>
        </div>
        <div>
          <h5><%= "Spotted at: #{@post.location}" %></h5>
        </div>
        <div>
          <h5><%= "Location: #{@post.address}"%><br>
            <%="#{@post.city}, #{@post.state}" %></h5>
          </div>

          <div>
            <h5><%= "Price:  #{@post.price}" %></h5>
          </div>

          <div>
            <h5>
              <%= "Posted By User: " %>
              <%=link_to @post.user.username, @post.user, {:style=>'color:#000000;', :class => "css_class"} %><br>
              <%="Posted on #{@post.created_at}"%>
            </h5>
          </div>

          <div class="postStaticMap">
            <span class="staticMapLink">Click To View/Hide Location</span>
            <div class="postStaticImage hidden">
              <% if @post.latitude.nil? || @post.longitude.nil? %>
              <h2>Location Details Invalid</h2>
              <% else %>
              <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@post.latitude},#{@post.longitude}&zoom=15&size=300x200&markers=color:red%7C#{@post.latitude},#{@post.longitude}"%>
              <% end %>
            </div>
          </div>
        </div>
    <% if !@post.comments.empty? %>
      <div class="postComments">
        <h4 id="commentsTitle">Comments</h4>
        <% @post.comments.each do |comment| %>
        <p>
          <strong><%= comment.user.username %></strong> -
          <%= comment.content %>
          <% if comment.user_id == current_user.id || current_user.id == @post.user_id%>
          <%= link_to "X", post_comment_path(@post, comment), method: :delete%>
          <% end %>
        </p>
        <% end %>
      </div>

    <% else %>
      <div class="postComments">
        <h4 id="commentsTitle">No Comments</h4>
      </div>
    <% end %>
    </div>
  </div>
</div>